


all: taskA taskB taskC

taskA: taskA.c
	gcc --std=gnu11 taskA.c -o taskA

taskB: taskB.c
	gcc --std=gnu11 taskB.c -o taskB
	gcc --std=gnu11 taskB2.c -o taskB2
	
taskC: taskC.c
	gcc --std=gnu11 taskC.c -o taskC